BSBookingQuery/Models/ErrorViewModel.cs
namespace BSBookingQuery.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BSBookingQuery/Controllers/AccountController.cs
using AutoMapper;
using BSBookingQuery.Domain.DTOs;
using BSBookingQuery.Domain.Entities;
using BSBookingQuery.Domain.Interfaces;
using BSBookingQuery.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace BSBookingQuery.Controllers
{
    [Route("[controller]/[action]")]
    public class AccountController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        public AccountController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> LogIn([FromBody]LogInDto logInDto)
        {
            var entity = await _unitOfWork.Accounts.LogIn(logInDto);
            return Json(entity);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Register([FromBody]RegisterDto registerDto)
        {
            var entity = await _unitOfWork.Accounts.Register(registerDto);
            _unitOfWork.Complete();
            return Json(entity);
        }

        [HttpGet]
        public JsonResult GetAllUserTypes()
        {
            var entity = _unitOfWork.Accounts.GetAllUserTypes();
            return Json(entity);
        }

    }
}

BSBookingQuery/Controllers/CommentController.cs
using AutoMapper;
using BSBookingQuery.Domain.DTOs;
using BSBookingQuery.Domain.Entities;
using BSBookingQuery.Domain.Interfaces;
using BSBookingQuery.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace BSBookingQuery.Controllers
{
    [Route("[controller]/[action]")]
    public class CommentController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CommentController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<JsonResult> GetAllComments()
        {
            var comments = await _unitOfWork.Comments.GetAllComments();
            return Json(comments);
        }

        [HttpPost]
        public int AddComment([FromBody] CommentDto commentDto)
        {
            CommentHistory entity = _mapper.Map<CommentHistory>(commentDto);
            _unitOfWork.Comments.Add(entity);
            return _unitOfWork.Complete();
        }
    }
}

BSBookingQuery/Controllers/HomeController.cs
using BSBookingQuery.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BSBookingQuery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BSBookingQuery/Controllers/HotelController.cs
using AutoMapper;
using BSBookingQuery.Domain.DTOs;
using BSBookingQuery.Domain.Entities;
using BSBookingQuery.Domain.Interfaces;
using BSBookingQuery.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace BSBookingQuery.Controllers
{
    [Route("[controller]/[action]")]
    public class HotelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public HotelController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAllHotels()
        {
            var hotels = await _unitOfWork.Hotels.GetAllHotels();
            return Json(hotels);
        }

        [HttpGet("{id}")]
        public async Task<JsonResult> GetHotelById(int id)
        {
            var hotel = await _unitOfWork.Hotels.Get(id);
            return Json(hotel);
        }

        [HttpPost]
        public int AddHotel([FromBody] HotelDto hotelDto)
        {
            Hotel entity = _mapper.Map<Hotel>(hotelDto);

            entity.HotelId = GenerateAutoHotelId.GenerateHotelId(entity.Name);

            _unitOfWork.Hotels.Add(entity);
            return _unitOfWork.Complete();
        }

        [HttpPut("{id}")]
        public async Task<int> UpdateHotel(int id, [FromBody] HotelDto hotelDto)
        {
            var entity = await _unitOfWork.Hotels.Get(id);

            if (entity != null)
            {
                _mapper.Map(hotelDto, entity);

                _unitOfWork.Hotels.Update(entity);
                return _unitOfWork.Complete();
            }

            return 0;
        }

        [HttpDelete("{id}")]
        public async Task<int> DeleteHotel(int id)
        {
            var entity = await _unitOfWork.Hotels.Get(id);

            if (entity != null)
            {
                _unitOfWork.Hotels.Delete(entity);
                return _unitOfWork.Complete();
            }

            return 0;
        }

        [HttpGet]
        public ActionResult Single()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> GetHotelsBySearchParam([FromBody] SearchParamDto searchParam)
        {
            var entity = await _unitOfWork.Hotels.GetHotelsBySearchParam(searchParam);
            return Json(entity);
        }

    }
}

BSBookingQuery/Controllers/LabelController.cs
using AutoMapper;
using BSBookingQuery.Domain.DTOs;
using BSBookingQuery.Domain.Entities;
using BSBookingQuery.Domain.Interfaces;
using BSBookingQuery.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace BSBookingQuery.Controllers
{
    [Route("[controller]/[action]")]
    public class LabelController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public LabelController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetAllLabels()
        {
            var labels = await _unitOfWork.Labels.GetAll();
            return Json(labels);
        }

        [HttpGet("{id}")]
        public async Task<JsonResult> GetLabelById(int id)
        {
            var label = await _unitOfWork.Labels.Get(id);
            return Json(label);
        }

        [HttpPost]
        public int AddLabel([FromBody]LabelDto labelDto)
        {
            Label entity = _mapper.Map<Label>(labelDto);

            _unitOfWork.Labels.Add(entity);
            return _unitOfWork.Complete();
        }

        [HttpPut("{id}")]
        public async Task<int> UpdateLabel(int id, [FromBody] LabelDto labelDto)
        {
            var entity = await _unitOfWork.Labels.Get(id);

            if (entity != null)
            {
                _mapper.Map(labelDto, entity);

                _unitOfWork.Labels.Update(entity);
                return _unitOfWork.Complete();
            }

            return 0;
        }

        [HttpDelete("{id}")]
        public async Task<int> DeleteLabel(int id)
        {
            var entity = await _unitOfWork.Labels.Get(id);

            if (entity != null)
            {
                _unitOfWork.Labels.Delete(entity);
                return _unitOfWork.Complete();
            }

            return 0;
        }

    }
}

BSBookingQuery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<script type="text/javascript">
    var app = angular.module('HomeApp', []);

    app.controller('HomeController', function ($scope, $http, $window) {

        $scope.lowerRatings = "0";
        $scope.higherRatings = "0";
        $scope.ratingsList = [
            {
                'id': 1,
                'name': '1'
            },
            {
                'id': 2,
                'name': '2'
            },
            {
                'id': 3,
                'name': '3'
            },
            {
                'id': 4,
                'name': '4'
            },
            {
                'id': 5,
                'name': '5'
            }
        ]

        $scope.SearchByName = () => {
            if (typeof $scope.searchName === 'undefined' || $scope.searchName == "") {
                alert('Search field is empty');
            }
            else {
                window.location.replace("/Hotel/List?search=" + $scope.searchName);
            }
        }

        $scope.SearchByRatings = () => {
            if (typeof $scope.lowerRatings === '0' || $scope.lowerRatings == "0") {
                alert('Lower ratings field is empty');
            }
            else if (typeof $scope.higherRatings === '0' || $scope.higherRatings == "0") {
                alert('Higher ratings field is empty');
            }
            else{
                window.location.replace("/Hotel/List?lower=" + $scope.lowerRatings + "&upper=" + $scope.higherRatings);
            }
        }

    });
</script>


<div ng-app="HomeApp">
    <div ng-controller="HomeController">
        <div class="container-fluid">
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" ng-model="searchName" aria-label="Search">
                <button class="btn btn-outline-success" type="submit" ng-click="SearchByName()">Search</button>
            </form>
        </div>
        <div class="container-fluid mt-3">
            <form class="d-flex">
                <select style="border: 1px solid #46b8da;" class="btn btn-default" ng-model="lowerRatings">
                    <option value="0">Lower Ratings</option>
                    <option ng-repeat="rating in ratingsList" value="{{rating.id}}">{{rating.name}}</option>
                </select>
                <select style="border: 1px solid #46b8da;" class="btn btn-default" ng-model="higherRatings">
                    <option value="0">Higher Ratings</option>
                    <option ng-repeat="rating in ratingsList" value="{{rating.id}}">{{rating.name}}</option>
                </select>
                <button class="btn btn-outline-success" type="submit" ng-click="SearchByRatings()">Search</button>
            </form>
        </div>
    </div>
</div>

BSBookingQuery/Views/Hotel/Index.cshtml
<script type="text/javascript">
    var app = angular.module('HotelCRUDApp', []);

    app.controller('HotelCRUDController', function ($scope, $http, $window) {
        $scope.locationDropdown = "0";

        $scope.LoadAllHotels = () => {
            $http.get("https://localhost:7132/Hotel/GetAllHotels", { headers: { 'Content-Type': 'application/json' } })
                .then(function (response) {
                    $scope.listOfHotel = response.data;
                }, function (error) {
                    alert("Failed to load hotels");
                });
        }

        $scope.GetLabelsList = () => {
            $http.get("https://localhost:7132/Label/GetAllLabels", { headers: { 'Content-Type': 'application/json' } })
                .then(function (response) {
                    $scope.listOfLabel = response.data;
                }, function (error) {
                    alert("Failed to load labels");
                });
        }

        $scope.AddNewHotel = function () {
            var hotelName = $scope.hotelName;
            var hotelName = $scope.hotelName;
            var hotelRatings = $scope.hotelRatings;
            var locationDropdown = $scope.locationDropdown;

            if (typeof hotelName === 'undefined' || hotelName == "") {
                alert('Name field is empty');
            }
            else if (typeof hotelRatings === 'undefined' || hotelRatings == "") {
                alert('Ratings field is empty');
            }
            else if (typeof locationDropdown === 'undefined' || locationDropdown == "") {
                alert('Location field is empty');
            }
            else {
                var hotelRequestModel = {
                    'Name': hotelName,
                    'Ratings': hotelRatings,
                    'LabelId': locationDropdown
                };

                $http.post("https://localhost:7132/Hotel/AddHotel", hotelRequestModel, { headers: { 'Content-Type': 'application/json' } })
                    .then(function (response) {
                        alert("Successful");
                        $('#createHotelModal').modal('hide');
                        $scope.LoadAllHotels();
                        $scope.ResetFields();
                    }, function (error) {
                        console.log(error);
                        alert("Failed");
                        $('#createHotelModal').modal('hide');
                        $scope.ResetFields();
                    })
            }
        }

        $scope.GetHotel = function (id) {
            $http.get("https://localhost:7132/Hotel/GetHotelById/" + id, { headers: { 'Content-Type': 'application/json' } })
                .then(function (response) {
                    $scope.editHotelId = id;
                    $scope.editName = response.data.name;
                    $scope.editRatings = response.data.ratings;
                    $scope.editLocationDropdown = response.data.labelId.toString();
                }, function (error) {
                    alert("Failed to get hotel");
                });
        }

        $scope.UpdateHotel = function () {
            var hotelId = $scope.editHotelId;
            var hotelName = $scope.editName;
            var hotelRatings = $scope.editRatings;
            var locationDropdown = $scope.editLocationDropdown;

            if (typeof hotelName === 'undefined' || hotelName == "") {
                alert('Name field is empty');
            }
            else if (typeof hotelRatings === 'undefined' || hotelRatings == "") {
                alert('Ratings field is empty');
            }
            else if (typeof locationDropdown === 'undefined' || locationDropdown == "") {
                alert('Location field is empty');
            }
            else {
                var hotelRequestModel = {
                    'Name': hotelName,
                    'Ratings': hotelRatings,
                    'LabelId': locationDropdown
                };

                $http.put("https://localhost:7132/Hotel/UpdateHotel/" + hotelId, hotelRequestModel, { headers: { 'Content-Type': 'application/json' } })
                    .then(function (response) {
                        alert("Successful");
                        $('#updateHotelModal').modal('hide');
                        $scope.LoadAllHotels();
                        $scope.ResetFields();
                    }, function (error) {
                        console.log(error);
                        alert("Failed");
                        $('#updateHotelModal').modal('hide');
                        $scope.ResetFields();
                    })
            }
        }

        $scope.DeleteHotel = function (id) {
            $http.delete("https://localhost:7132/Hotel/DeleteHotel/" + id)
                .then(function (response) {
                    alert("Successful");
                    $scope.LoadAllHotels();
                }, function (error) {
                    console.log(error);
                    alert("Failed");
                })
        }

        $scope.ResetFields = function () {
            $scope.hotelName = "";
            $scope.hotelRatings = "";
            $scope.locationDropdown = "0";
        }

    });
</script>

<div ng-app="HotelCRUDApp">
    <div ng-controller="HotelCRUDController" ng-init="LoadAllHotels()">
        <h1>Hotels</h1>

        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createHotelModal">
            Create New Hotel
        </button>

        <!-- Add New Hotel Modal -->
        <div class="modal fade" id="createHotelModal" tabindex="-1" aria-labelledby="createHotelModal" aria-hidden="true" ng-init="GetLabelsList()">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Hotel Information</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="mb-3">
                            <label for="hotelName" class="form-label">Name</label>
                            <input type="text" class="form-control" id="hotelName" ng-model="hotelName" autocomplete="off">
                        </div>
                        <div class="mb-3">
                            <label for="hotelRatings" class="form-label">Ratings</label>
                            <input type="text" class="form-control" id="hotelRatings" ng-model="hotelRatings" autocomplete="off">
                        </div>
                        <div class="mb-3">
                            <label for="locationDropdown" class="form-label">Location</label>
                            <select style="border: 1px solid #46b8da;" class="btn btn-default" ng-model="locationDropdown">
                                <option value="0">Select Location</option>
                                <option ng-repeat="label in listOfLabel" value="{{label.id}}">{{label.location}}</option>
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" ng-click="AddNewHotel()">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <table class="table mt-5">
            <thead>
                <tr>
                    <th>Hotel Id</th>
                    <th>Name</th>
                    <th>Ratings</th>
                    <th>Location</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="hotel in listOfHotel track by $index">
                    <td>{{hotel.hotelId}}</td>
                    <td>{{hotel.name}}</td>
                    <td>{{hotel.ratings}}</td>
                    <td>{{hotel.label.location}}</td>
                    <td>
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#updateHotelModal" ng-click="GetHotel(hotel.id)">
                        Edit
                        </button>
                        <button type="button" class="btn btn-danger" ng-click="DeleteHotel(hotel.id)">
                        Delete
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>

        <!-- Edit New Hotel Modal -->
        <div class="modal fade" id="updateHotelModal" tabindex="-1" aria-labelledby="updateHotelModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Hotel Information</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3" style="display: none;">
                            <input type="text" class="form-control" id="editHotelId" ng-model="editHotelId" autocomplete="off">
                    </div>
                    <div class="mb-3">
                        <label for="editName" class="form-label">Name</label>
                            <input type="text" class="form-control" id="editName" ng-model="editName" autocomplete="off">
                    </div>
                    <div class="mb-3">
                            <label for="editRatings" class="form-label">Ratings</label>
                            <input type="text" class="form-control" id="editRatings" ng-model="editRatings" autocomplete="off">
                        </div>
                        <div class="mb-3">
                            <label for="editLocationDropdown" class="form-label">Location</label>
                            <select style="border: 1px solid #46b8da;" class="btn btn-default" ng-model="editLocationDropdown">
                                <option value="0">Select Location</option>
                                <option ng-repeat="label in listOfLabel" value="{{label.id}}">{{label.location}}</option>
                            </select>
                        </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" ng-click="UpdateHotel()">Update</button>
                </div>
            </div>
        </div>
    </div>
    
    </div>
</div>

BSBookingQuery/Views/Hotel/List.cshtml
<script type="text/javascript">
    var app = angular.module('HotelListApp', []);

    app.controller('HotelListController', function ($scope, $http, $window) {

        $scope.ListOfHotels = () => {
            const queryString = window.location.search;
            const urlParams = new URLSearchParams(queryString);
            if (urlParams.has('search')) {
                const searchParam = urlParams.get('search');
                console.log(searchParam);

                var searchRequestBodyModel = {
                    "name": searchParam
                };

                $scope.SearchHotelByParams(searchRequestBodyModel);
            }
            else if (urlParams.has('lower') && urlParams.has('upper')) {
                const lowerParam = urlParams.get('lower');
                const upperParam = urlParams.get('upper');
                console.log(lowerParam);
                console.log(upperParam);

                var searchRequestBodyModel = {
                    "lowerRatings": lowerParam,
                    "upperRatings": upperParam
                };

                $scope.SearchHotelByParams(searchRequestBodyModel);
            }
        }

        $scope.SearchHotelByParams = (searchRequestBodyModel) => {
            $http.post("https://localhost:7132/Hotel/GetHotelsBySearchParam", searchRequestBodyModel, { headers: { 'Content-Type': 'application/json' } })
                .then(function (response) {
                    $scope.hotels = response.data;
                }, function (error) {
                    console.log(error);
                    alert("Failed");
                })
        }

        $scope.Navigate = (id) => {
            window.location.replace("/Hotel/Single?id=" + id);
        }

    });
</script>



<div ng-app="HotelListApp">
    <div ng-controller="HotelListController">
        <div class="container-fluid" ng-init="ListOfHotels()">
            <div class="card" ng-repeat="hotel in hotels">
                <div class="row" ng-click="Navigate(hotel.id)" style="cursor: pointer;">
                    <div class="col-md-4">
                        <img src="/images/hotel.png" alt="hotel.png" class="img-fluid rounded-start" />
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h4>Hotel Id: {{hotel.hotelId}}</h4>
                            <h4>Hotel Name: {{hotel.name}}</h4>
                            <h4>Ratings: {{hotel.ratings}}</h4>
                            <h4>Location: {{hotel.label.location}}</h4>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

BSBookingQuery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BSBookingQuery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BSBookingQuery.styles.css" asp-append-version="true" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.3/angular.min.js"></script>

</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BSBookingQuery</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Label" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Hotel</a>
                        </li>
                    </ul>
                    <ul>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>*@

        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BSBookingQuery</a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item" id="LabelShow">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Label" asp-action="Index">Locations</a>
                        </li>
                        <li class="nav-item" id="HotelShow">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hotel" asp-action="Index">Hotel</a>
                        </li>
                    </ul>
                    <div class="d-flex">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>

    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BSBookingQuery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            var typeName = localStorage.getItem("userTypeName");

            if (typeName == null || typeName == "null") {
                var label = document.getElementById('LabelShow');
                label.style.display = 'none'; //or
                label.style.visibility = 'hidden';

                var hotel = document.getElementById('HotelShow');
                hotel.style.display = 'none'; //or
                hotel.style.visibility = 'hidden';
            }
            else if (typeName === "Guest") {
                var label = document.getElementById('LabelShow');
                label.style.display = 'none'; //or
                label.style.visibility = 'hidden';

                var hotel = document.getElementById('HotelShow');
                hotel.style.display = 'none'; //or
                hotel.style.visibility = 'hidden';
            }
            else if (typeName === "NormalUser") {
                var label = document.getElementById('LabelShow');
                label.style.display = 'block'; //or
                label.style.visibility = 'visible';

                var hotel = document.getElementById('HotelShow');
                hotel.style.display = 'block'; //or
                hotel.style.visibility = 'visible';
            }
        });
    </script>
</body>
</html>